### ISSUE TITLE
Missing interactive shell in viewer

### ISSUE THREAD

**Issue by bdackley** [agstn/dataxray#2]
I've gone through the tutorial, and can export the code as html, where I have the interactive shell (Variable TYPE though Variable DISTINCT), but that is not present in the R Studio IDE Viewer pane.  I'm not sure if that's an issue, or that is how this should work, but it would be good to clarify if I'm missing something or not. 

I'm using RStudio 2021.09.0+351 "Ghost Orchid" Release, and R 4.1.1. 

![Viewer1](https://user-images.githubusercontent.com/104519820/165577875-3a329bcb-474d-4e11-bedd-16a327d325b9.jpeg)

**Comment by sjlussier** [comment]
This behavior is expected - the sidebar is only invoked with the use of dataxray::report_xray() which renders the .html document that contains the sidebar as well as the interactive table. 

It is possible that we could implement a new function in a future version of dataxray that would allow for viewing in the RStudio Viewer Pane.
