### ISSUE TITLE
no applicable method for 'create_hist' applied to an object of class "logical"

### ISSUE THREAD

**Issue by njss** [agstn/dataxray#8]
Quitting from lines 51-54 (ggplot2_Test_xray.rmd) 
Error in `mutate()`:
! Problem while computing `spike_hist = list(create_hist(x, counts, values))`.
ℹ The error occurred in row 32.
Caused by error in `UseMethod()`:
! no applicable method for 'create_hist' applied to an object of class "logical"
Backtrace:
  1. dataxray::make_xray(data, by = params$by)
 10. dataxray::create_hist(x, counts, values)

**Comment by JunjieLeiCoe** [comment]
Same issue 


```R 
> df_cln %>% make_xray() %>% view_xray()
Error in `mutate()`:
i In argument: `spike_hist = list(create_hist(x, counts, values))`.
i In row 6.
Caused by error in `UseMethod()`:
! no applicable method for 'create_hist' applied to an object of class "logical"
Run `rlang::last_trace()` to see where the error occurred.
Warning message:
There was 1 warning in `mutate()`.
i In argument: `describe = ... %>% list()`.
i In row 6.


```
